### ISSUE TITLE
Unknown parameter: ?2004

### ISSUE THREAD

**Issue by SnirkImmington** [Immington-Industries/rust-wlc#15]
Using the example compositor for some time will yield output:

```
Unknown parameter: ?2004
Unknown parameter: ?2004
Unknown parameter: ?2004
Unknown parameter: ?2004
Unknown parameter: ?2004
```

The number is 2004 in  different sessions. This isn't being passed through wlc's standard logging channel - we're not picking it up in our log callback.

This is either a wlc issue or we're passing bad input somewhere.

**Comment by Timidger** [comment]
Is time the only factor? Does it only happen when certain actions are taken? Does it matter what programs/types of programs are being ran?

**Comment by SnirkImmington** [comment]
Once on `ctrl+enter`, twice on regular `enter`...

**Comment by SnirkImmington** [comment]
I can't find `Unknown parameter` in wlc's source, this is probably a wayland bug.

**Comment by SnirkImmington** [comment]
I just realized this doesn't show up in the latest wlc example (and it does on ours).

**Comment by SnirkImmington** [comment]
This is printed every time weston-terminal is launched or closed. It is their bug, not ours.
