### ISSUE TITLE
Things we're currently missing from the wlc API

### ISSUE THREAD

**Issue by SnirkImmington** [Immington-Industries/rust-wlc#25]
Here's a list of functions from the wlc API that we have not implemented yet:

:x: `wlc_exec` - Rust already supplies this.
- [x]  Functions with `wlc_resource` or `wl_resource` - Some of these require partial bindings to wayland, and `wlc_resource` seems ill-defined/we don't get it.
- [x] `wlc_handle_{get,set}_userdata` - Uses a `void*` and is under-documented. We've also split `wlc_handle` up and would need to take that into account.

**Optional bindings for wayland features** - using an existing Rust crate as an optional dependency for wayland bindings, add the wayland features `wlc` exports. Put this under a feature.
- [x] `wlc_wayland.h`
- [ ] `wlc-render.h`

If you have a pull request for any of these features you'd like to submit, we would be very appreciative.

Otherwise, if there's something that we've left out because we didn't RTFM and you have a manual, please point us to it and we'll add it to our to do list.

**Comment by SnirkImmington** [comment]
Added wlc_handle_get/set_user_data

**Comment by SnirkImmington** [comment]
Add optional dependency for wayland stuff

**Comment by Timidger** [comment]
This will be fixed #62 is merged in.
