### ISSUE TITLE
Mouse sometimes dissapears

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/rust-wlc#4]

**Comment by SnirkImmington** [comment]
I think it disappears after a window opens and doesn't reappear until you move over the background and back over the window.

**Comment by Timidger** [comment]
Yeah that's when I've noticed it too. Not sure where the issue might be, but that at least narrows it down significantly...

Perhaps a get_top_most call or something?

**Comment by SnirkImmington** [comment]
No windows -> create window -> mouse disappears -> mouse leave window -> mouse appears, stays over window

This happens after closing all windows and trying again.

If multiple windows are open, the same thing happens. When the mouse leaves the first window that blocked it, it appears again (i.e. over a second window opened).

**Comment by SnirkImmington** [comment]
Possibly fixed in wlc?
