### ISSUE TITLE
Mouse "curves" towards window buttons and window borders

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/rust-wlc#5]
Moving the mouse back and forth eventually causes the mouse to reach the top of the screen

**Comment by SnirkImmington** [comment]
This issue isn't mentioned in wlc, sway, or orbment.

**Comment by Timidger** [comment]
I brought it up on Sway, they decided it's either a bug in WLC/libinput or it might be a consequence of mouse acceleration. See it [here](https://github.com/SirCmpwn/sway/issues/491)

**Comment by Timidger** [comment]
Refer to [this issue](https://github.com/Cloudef/wlc/issues/126) for all further discussion, this will remain open until the bug is fixed.

**Comment by Timidger** [comment]
though this is labelled as a WLC bug, this bug actually occurs in libinput. The fix for now is to install a version of the library <= 1.1.5.
