### ISSUE TITLE
Performance Enhancements

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/rust-wlc#7]
It's a bit of a CPU hog sometimes, probably just have to cut back on the rendering

**Comment by SnirkImmington** [comment]
Do you think the issue's mostly with moving and resizing?

**Comment by Timidger** [comment]
It probably is, so code dealing with window moving/resizing is probably where the issue is. More ad-hoc testing might be required though to narrow down if there are other possible suspects (but it's probably that)

**Comment by SnirkImmington** [comment]
Can we do some testing to make sure this isn't a wlc issue? Our example shouldn't be calling more involved code than theirs - unless the use of `RwCell` in critical functions (like open for read, close open for write) is the issue.

**Comment by SnirkImmington** [comment]
I have seen no indications that this is a real issue with wlc or our bindings.
